Repository SimonBlanke/Hyperactive, pull requests merged in 2025-07, with the labels that each got.

#139 Feature/random search sk
  src/hyperactive/opt/__init__.py
  src/hyperactive/opt/random_search.py
Labels: enhancement

#138 Feature/sklearn v1.7
  .github/workflows/test.yml
  src/hyperactive/integrations/sklearn/_compat.py
  src/hyperactive/integrations/sklearn/best_estimator.py
  src/hyperactive/integrations/sklearn/hyperactive_search_cv.py
  src/hyperactive/integrations/sklearn/opt_cv.py
Labels: bug

#142 [ENH] sign handling in experiments and optimization
  extension_templates/experiments.py
  extension_templates/optimizers.py
  src/hyperactive/base/_experiment.py
  src/hyperactive/base/_optimizer.py
  src/hyperactive/experiment/integrations/sklearn_cv.py
  src/hyperactive/experiment/toy/_ackley.py
  src/hyperactive/experiment/toy/_parabola.py
  src/hyperactive/experiment/toy/_sphere.py
  src/hyperactive/tests/test_all_objects.py
Labels: enhancement

#145 [MNT] raise `scikit-learn` bound to `scikit-learn<1.8`
  pyproject.toml
Labels: maintenance

#149 [MNT] raise `scikit-learn` bound to `scikit-learn<1.8`
  pyproject.toml
Labels: maintenance
